# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(878, 600)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(70, 60, 321, 391))
        self.frame.setStyleSheet("#frame{\n"
"background-color: qlineargradient(spread:pad, x1:0.295, y1:0.0113636, x2:0.653, y2:0.914773, stop:0 rgba(21, 127, 130, 255), stop:1 rgba(255, 255, 212, 255));\n"
"border-radius:20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 140, 191, 91))
        self.label.setStyleSheet("font: 75 20pt \"Microsoft JhengHei UI\";")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(380, 70, 351, 371))
        self.frame_2.setStyleSheet("#frame_2{\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(310, 0, 41, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-top:2px;\n"
"}\n"
"")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/close2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 40, 341, 321))
        self.frame_3.setMinimumSize(QtCore.QSize(341, 321))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"    border-bottom:1px solid black;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}\n"
"")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_Login = QtWidgets.QWidget()
        self.page_Login.setObjectName("page_Login")
        self.gridLayout = QtWidgets.QGridLayout(self.page_Login)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_L_username = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_L_username.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_L_username.setStyleSheet("font: 9pt \"Microsoft JhengHei UI\";")
        self.lineEdit_L_username.setText("")
        self.lineEdit_L_username.setObjectName("lineEdit_L_username")
        self.gridLayout.addWidget(self.lineEdit_L_username, 0, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(47, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(46, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 3, 1, 1)
        self.lineEdit_L_password = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_L_password.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_L_password.setStyleSheet("font: 9pt \"Microsoft JhengHei UI\";")
        self.lineEdit_L_password.setText("")
        self.lineEdit_L_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_L_password.setObjectName("lineEdit_L_password")
        self.gridLayout.addWidget(self.lineEdit_L_password, 1, 0, 1, 4)
        self.pushButton_L_sure = QtWidgets.QPushButton(self.page_Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_L_sure.sizePolicy().hasHeightForWidth())
        self.pushButton_L_sure.setSizePolicy(sizePolicy)
        self.pushButton_L_sure.setMinimumSize(QtCore.QSize(200, 35))
        self.pushButton_L_sure.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_L_sure.setStyleSheet("font: 75 9pt \"微软雅黑\";")
        self.pushButton_L_sure.setObjectName("pushButton_L_sure")
        self.gridLayout.addWidget(self.pushButton_L_sure, 5, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_Login)
        self.page_Register = QtWidgets.QWidget()
        self.page_Register.setObjectName("page_Register")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_Register)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(47, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 0, 1, 1)
        self.lineEdit_R_username = QtWidgets.QLineEdit(self.page_Register)
        self.lineEdit_R_username.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_username.setStyleSheet("font: 9pt \"Microsoft JhengHei UI\";")
        self.lineEdit_R_username.setObjectName("lineEdit_R_username")
        self.gridLayout_2.addWidget(self.lineEdit_R_username, 0, 0, 1, 4)
        self.lineEdit_R_password = QtWidgets.QLineEdit(self.page_Register)
        self.lineEdit_R_password.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_password.setStyleSheet("font: 9pt \"Microsoft JhengHei UI\";")
        self.lineEdit_R_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_R_password.setObjectName("lineEdit_R_password")
        self.gridLayout_2.addWidget(self.lineEdit_R_password, 1, 0, 1, 4)
        spacerItem4 = QtWidgets.QSpacerItem(46, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 3, 3, 1, 1)
        self.lineEdit_R_password_re = QtWidgets.QLineEdit(self.page_Register)
        self.lineEdit_R_password_re.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_R_password_re.setStyleSheet("font: 9pt \"Microsoft JhengHei UI\";")
        self.lineEdit_R_password_re.setText("")
        self.lineEdit_R_password_re.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_R_password_re.setObjectName("lineEdit_R_password_re")
        self.gridLayout_2.addWidget(self.lineEdit_R_password_re, 2, 0, 1, 4)
        self.pushButton_R_register = QtWidgets.QPushButton(self.page_Register)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_R_register.sizePolicy().hasHeightForWidth())
        self.pushButton_R_register.setSizePolicy(sizePolicy)
        self.pushButton_R_register.setMinimumSize(QtCore.QSize(200, 35))
        self.pushButton_R_register.setStyleSheet("font: 75 9pt \"微软雅黑\";")
        self.pushButton_R_register.setObjectName("pushButton_R_register")
        self.gridLayout_2.addWidget(self.pushButton_R_register, 3, 2, 1, 1)
        self.stackedWidget_2.addWidget(self.page_Register)
        self.horizontalLayout_2.addWidget(self.stackedWidget_2)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Login = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Login.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}\n"
"    ")
        self.pushButton_Login.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Login.setIcon(icon1)
        self.pushButton_Login.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.horizontalLayout.addWidget(self.pushButton_Login)
        self.pushButton_Register = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Register.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:3px;\n"
"    padding-left:3px;\n"
"}\n"
"    ")
        self.pushButton_Register.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/register.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Register.setIcon(icon2)
        self.pushButton_Register.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_Register.setObjectName("pushButton_Register")
        self.horizontalLayout.addWidget(self.pushButton_Register)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_2.raise_()
        self.frame.raise_()
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.stackedWidget_2.setCurrentIndex(0)
        self.pushButton.clicked.connect(LoginWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)
        LoginWindow.setTabOrder(self.lineEdit_L_username, self.lineEdit_L_password)
        LoginWindow.setTabOrder(self.lineEdit_L_password, self.pushButton_L_sure)
        LoginWindow.setTabOrder(self.pushButton_L_sure, self.lineEdit_R_username)
        LoginWindow.setTabOrder(self.lineEdit_R_username, self.lineEdit_R_password)
        LoginWindow.setTabOrder(self.lineEdit_R_password, self.lineEdit_R_password_re)
        LoginWindow.setTabOrder(self.lineEdit_R_password_re, self.pushButton_R_register)
        LoginWindow.setTabOrder(self.pushButton_R_register, self.pushButton_Login)
        LoginWindow.setTabOrder(self.pushButton_Login, self.pushButton_Register)
        LoginWindow.setTabOrder(self.pushButton_Register, self.pushButton)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label.setText(_translate("LoginWindow", "Welcome Back"))
        self.lineEdit_L_username.setPlaceholderText(_translate("LoginWindow", "UserName："))
        self.lineEdit_L_password.setPlaceholderText(_translate("LoginWindow", "Password："))
        self.pushButton_L_sure.setText(_translate("LoginWindow", "LOGIN"))
        self.lineEdit_R_username.setPlaceholderText(_translate("LoginWindow", "UserName："))
        self.lineEdit_R_password.setPlaceholderText(_translate("LoginWindow", "Password："))
        self.lineEdit_R_password_re.setPlaceholderText(_translate("LoginWindow", "Resign Password："))
        self.pushButton_R_register.setText(_translate("LoginWindow", "REGISTER"))
import res_rc
